---

- hosts: all
  tasks:
  - name: Ping
    ping:
  - name: Debug
    ansible.builtin.debug:
      msg:
      - "os_family: {{ ansible_facts['os_family'] }}"
      - "inventory_hostname: {{ inventory_hostname }}"
      - "ansible_host: {{ ansible_host }}"
  - include_role:
      name: nixos-update-config

- hosts: servers
  tasks:
  - include_role:
      name: dockge
  - include_role:
      name: homepage
