services:
  dockge:
    image: louislam/dockge:${IMAGE_VERSION}
    restart: unless-stopped
    networks:
      traefik_reverse_proxy:
    ports:
      - ${HOST_PORT}:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      DOCKGE_STACKS_DIR: /opt/stacks
    env_file: ./.env
    labels:
      - homepage.group=${ANSIBLE_HOST} services
      - homepage.name=Dockge
      - homepage.icon=dockge.png
      - homepage.href=https://dockge.${ANSIBLE_HOST}/
      - homepage.description=Dockge
      - 'traefik.enable=true'
      - "traefik.http.routers.dockge.entrypoints=http"
      - "traefik.http.routers.dockge.rule=Host(`dockge.${ANSIBLE_HOST}`)"
      - "traefik.http.middlewares.dockge-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dockge.middlewares=dockge-https-redirect"
      - 'traefik.http.routers.dockge-secure.rule=Host(`dockge.${ANSIBLE_HOST}`)'
      - 'traefik.http.routers.dockge-secure.entrypoints=https'
      - 'traefik.http.routers.dockge-secure.tls=true'
      - 'traefik.http.services.dockge-secure.loadbalancer.server.port=${HOST_PORT}'
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.dockge-secure.middlewares=authelia@docker"

networks:
  traefik_reverse_proxy:
    external: true