version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    labels:
      - homepage.group=Services
      - homepage.name=Dockge
      - homepage.icon=dockge.png
      - homepage.href=http://10.10.10.10:5001/
      - homepage.description=Dockge
