  - name: Deny all traffic
    become: yes
    community.general.ufw:
      state: enabled
      direction: incoming
      policy: deny

  - name: Allow all access to tcp port 22
    become: yes
    community.general.ufw:
      rule: allow
      port: '22'
      proto: tcp
