services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${IMAGE_VERSION}
    container_name: homepage
    restart: unless-stopped
    networks:
      traefik_reverse_proxy:
    ports:
      - ${HOST_PORT}:5000
    environment:
      PORT: 5000
    env_file:
      - path: ./.env
        required: true
    volumes:
      - /opt/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - homepage.group=Services
      - homepage.name=Homepage
      - homepage.icon=homepage.png
      - homepage.href=https://${ANSIBLE_HOST}/
      - homepage.description=Homepage
      - 'traefik.enable=true'
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`${ANSIBLE_HOST}`)"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - 'traefik.http.routers.homepage-secure.rule=Host(`${ANSIBLE_HOST}`)'
      - 'traefik.http.routers.homepage-secure.entrypoints=https'
      - 'traefik.http.routers.homepage-secure.tls=true'
      - 'traefik.http.services.homepage-secure.loadbalancer.server.port=${HOST_PORT}'
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

networks:
  traefik_reverse_proxy:
    external: true
