version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - /opt/homebridge:/homebridge
    ports:
      - 8581:8581
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    labels:
      - homepage.group=Services
      - homepage.name=Homebridge
      - homepage.icon=homepage.png
      - homepage.href=http://10.10.10.10:8581/
      - homepage.description=Homebridge
