---

- hosts: all
  tasks:
  - name: Debug
    ansible.builtin.debug:
      msg:
      - "os_family: {{ ansible_facts['os_family'] }}"
      - "inventory_hostname: {{ inventory_hostname }}"
      - "ansible_host: {{ ansible_host }}"
      - "domain_name: {{ domain_name }}"
  - include_role:
      name: nixos-update-config

- hosts: core
  vars:
    CF_DNS_API_TOKEN: "{{cf_dns_api_token_core}}"
  tasks:
  - include_role:
      name: dockge
  - include_role:
      name: homepage
  - include_role:
      name: homebridge
  - include_role:
      name: pihole

- hosts: cloud
  vars:
    CF_DNS_API_TOKEN: "{{cf_dns_api_token_cloud}}"
  tasks:
  - include_role:
      name: allow-only-ssh
  - include_role:
      name: authelia
  - include_role:
      name: dockge
  - include_role:
      name: homepage
  - include_role:
      name: mealie
  - include_role:
      name: traefik

