  - include_role:
      name: prepare-docker-compose

  - name: Check for directory
    stat:
      path: /opt/stacks/dockge
    register: directory_check

  - name: Creates directory
    become: yes
    ansible.builtin.file:
      path: /opt/stacks/dockge
      state: directory
      owner: docker
      group: docker
      mode: 0775
      recurse: yes
    when: not directory_check.stat.exists

  - name: Copy environment file
    become: yes
    ansible.builtin.template:
      src: files/env.j2
      dest: /opt/stacks/dockge/.env
      owner: docker
      group: docker
      mode: 0644
    register: env_file
    no_log: True

  - name: Copy docker-compose.yml
    become: yes
    ansible.builtin.copy:
      src: files/docker-compose.yml
      dest: /opt/stacks/dockge/docker-compose.yml
      owner: docker
      group: docker
      mode: 0644
    register: compose_file

  - name: Create and start services
    become: yes
    community.docker.docker_compose_v2:
      project_src: /opt/stacks/dockge
      files:
      - docker-compose.yml

  - name: Restart services
    become: yes
    ansible.builtin.command: docker compose -f /opt/stacks/dockge/docker-compose.yml restart
    when:
      - not compose_file.changed
      - env_file.changed
